const { StyleSheet } = require("react-native");

const styles = StyleSheet.create({
  container:{
    flex:1,
    height:800,
  },
  details:{
    padding:20,
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#DEDCDB',
  },
  name:{
    fontSize:40,
    fontWeight:'bold',
    borderWidth:1,
    padding:10,
    paddingLeft:30,
    paddingRight:30,
    borderRadius:10,
    overflow:'hidden',
    backgroundColor:'#51BDD6',
    width:360,
  },
  type:{
    fontSize:25,
    marginTop:10,
    fontWeight:'bold',
    borderWidth:1,
    padding:10,
    paddingLeft:30,
    paddingRight:30,
    borderRadius:10,
    width:360,
    backgroundColor:'#A1C740',
    overflow:'hidden'
  },
  typeAlcohlic:{
    fontWeight:'normal',
  },
  glass:{
    fontSize:25,
    marginTop:10,
    fontWeight:'bold',
    borderWidth:1,
    padding:10,
    paddingLeft:30,
    paddingRight:30,
    borderRadius:10,
    width:360,
    backgroundColor:'#E0C651',
    overflow:'hidden'
  },
  typeGlass:{
    fontWeight:'normal',
  },
  viewIngredient:{
    flex:1,
    justifyContent:'center',
    alignItems:'center',
    borderWidth:1,
    padding:10,
    borderRadius:10,
    marginTop:10,
    width:360,
    backgroundColor:'#E08934'
  },
  ingredient:{
    fontSize:30,
    fontWeight:'bold',
  },
  ingredientItem:{
    fontSize:25,
    marginTop:10,
  },
  viewInstruction:{
    flex:1,
    justifyContent:'center',
    alignItems:'center',
    borderWidth:1,
    padding:10,
    paddingLeft:30,
    paddingRight:30,
    borderRadius:10,
    marginTop:10,
    width:360,
    backgroundColor:'#E06233',
  },
  instruction:{
    fontSize:25,
    fontWeight:'bold', 
  },
  instructionPrepare:{
    fontSize:25,
    marginTop:10,
    fontWeight:'normal',
  }
})

export default styles;